DataDog/Miscellany

- migrate_dashboard.py
Add migrate_dashboard script to pull dash from 1 account and send to another
> Add migrate_dashboard script

- dashconverter.py
adding check if title_text exists and is a string else use the query as graph title
> adding check if title_text exists and is a string

- .gitignore
- get_all_boards/README.md
- get_all_boards/get_all_boards.py
- get_all_boards/requirements.txt
A script that will get all dashboards for an organization and print out the json. Good for giving to customers to find malformed values submitted via the API.
> Code for get all boards

- dashconverter.py
Fixes broken dashes when converting TB to SB when the TB has template vars.  Also, if no title is specified, create one based off of current title.
> Pull in template vars for timeboards as well and create title based off of converted dash

- fullmetrics_dash.py
Attachment of KB: https://help.datadoghq.com/hc/en-us/articles/215681223
> adding full_metrics dashboard script

- README.md
See preview here: https://github.com/DataDog/Miscellany/blob/ckelner/readmeupdates/README.md#miscellany
> Add all scripts to readme in tabular format

- clean_up_stale.py
- remove_old_dash_monitors/README.md
- remove_old_dash_monitors/remove_old_dash_monitors.py
@johananlai - mind if we get these changes into our DD repo! This LGTM!
> Merging into DD

- README.md
- query_hosts_create_tags.py
script queries hosts api using pagination and adds tags to hosts based off of some property
> script queries hosts api using pagination and creates new tags

- migrate_monitors.py
update so you can search by any monitor key / value where the value is a string
> add other search options

- README.md
- create_email_list.py
creates a CSV file in the same directory containing a list of all user log in handles
> creates a CSV file containing a list of all user log in handles

- README.md
- Send_filesystem_events/README.MD
- Send_filesystem_events/send_filesystem_events.py
Add a script and README to send an event to the event stream when it detects a change in the directory it is watching.
> Laura.hampton/inotify directory script

- migrate_dashboard.py
These edits serve to update the script to match the updated Dashboard API endpoint, which unifies the screenboard and timeboard APIs ([see docs](https://docs.datadoghq.com/api/?lang=python#dashboards) for additional details)
> Updating script to reflect updated Dashboard API

- dashconverter/dashconverter.py
I had a timeboard with notes in it, that I wanted to convert to a screenboard.
This solution worked for me.  So, I thought I would propose a change.
> fix(note) - note for timeboard to screenboard

- Dashboards/migrate_dashboard.py
Created a dashboard migration script, as the timeboard and screenboard scripts are outdated since we changed our API endpoints. The dashboard migration script will work for both timeboards and screenboards.
> Create migrate dashboard script

- Dogmover/dogmover.py
You can now export and import AWS accounts
> Added Support for migrating AWS Accounts

- Dogmover/.gitignore
- Dogmover/Dockerfile
- Dogmover/README.md
- Dogmover/dogmover.py
Add migration option for log pipelines
Add utilization via docker
> Add logpipeline migration and docker usage

- log-downloader/README.md
- log-downloader/requirements.txt
- log-downloader/widget_updater.py
- This PR adds a little Python utility which would allow you to go through all your dashboards and batch update a metric name.
> Add Widget Updater Script

- dd-example/README.md
> Update README.md to fix a typo

- Dogmover/dogmover.py
Added dry-run on pull awsaccounts as well
> Fixed dry-run on pull awsaccounts

- README.md
- get_active_users/README.md
- get_active_users/get_active_users.py
Collects a list of all active (ie. non disabled or pending) users in an organization to a csv file.
> Add get_active_users script

- fullmetrics_dash.py
This update allows use with the EU instance using the `-eu` flag.
> Updates fullmetrics_dash.py for use with EU instance

- Dogmover/README.md
- Dogmover/dogmover.py
Simple change to add SLO pull/push to Dogmover
> Add support for SLOs to Dogmover

- Dogmover/README.md
Dogmover has been a very good pal over the past years, you will be missed
> Deprecate dogmover

- synthetics/uptime-reporting/extract-synthetics-uptimes.py
- synthetics/uptime-reporting/readme.md
- synthetics/uptime-reporting/requirements.txt
This PR adds a script to export Synthetics uptimes (csv format).
> Add script to extract Synthetics uptimes
